language: c
os: linux
sudo: true

env:
  - DIST=fedora
#  - DIST=centos8

before_install:
  - . /etc/os-release
  - sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman

script:
  - podman build -t $DIST .
  - podman run $DIST
