name: cppcheck
on:
  push:
    ## FIXME: add [main]
  pull_request:
  schedule:
    - cron: '30 0 * * *'
jobs:
  cppcheck_create_base:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt update
          sudo apt install -y cppcheck

      - name: Execute cppcheck
        run: cppcheck --enable=all --inconclusive --std=c++20 --output-file=cppcheck_report.txt .

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-base-${{ steps.date.outputs.date }}
          path: cppcheck_report.txt

  cppcheck_run_diff:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get base coverity scan
        run: |
          curl -H "Accept: application/vnd.github.v3+json" $REPO_URL | jq ".artifacts[] | select(.name==\"$FILENAME\") | .url"
        env:
          REPO_URL: https://api.github.com/repos/justin-stephenson/tlog/actions/artifacts
          FILENAME: cppcheck-base-${{ steps.date.outputs.date }}
